---
- name: DEPLOYMENT ON EKS
  hosts: tag_eks_master_server
  remote_user: ubuntu
  tasks:  
    - name: CREATE PLAYBOOKS DIR ON EKS CLUSTER
      file:
        path: /opt/playbooks
        state: directory
        mode: "0755"
      become: true     

    - name: COPY DEPLOYMENT FILE
      copy:
        src: /var/lib/jenkins/workspace/JOB_NAME/playbooks/dep_svc.yml
        dest: /opt/playbooks
      become: true

    - name: CHECK FILE
      shell: ls -l /opt/playbooks/
      register: copy
      become: true        

    - name: DEPLOYMENT FILE COPY STATUS      
      debug:
        var: copy.stdout_lines              
        
    - name: DEPLOYMENT ON K8 CLUSTER
      shell: /home/ubuntu/kubectl apply -f /opt/playbooks/dep_svc.yml
      register: deployment

    - name: DEPLOYMENT STATUS      
      debug:
        var: deployment.stdout_lines

    - name: WAITING FOR GET DEPLOYMENT STATUS
      shell: sleep 100      

    - name: STATUS OF DEPLOYMENT
      shell: /home/ubuntu/kubectl get pod
      register: get_deployment_status

    - name: PRINT DEPLOYMENT STATUS
      debug:
        var: get_deployment_status.stdout_lines
