---
- name: CREATE DIRECTORY & COPY FILES
  hosts: tag_eks_master_server
  become: true
  vars:
    ansible_ssh_private_key_file: /etc/ansible/terraform_ansible.pem
  tasks:
    - name: CREATE DOCKER DIRECTORY
      file:
        path: /opt/docker
        state: directory
        mode: "0755"      

    - name: COPY DOCKERFILE
      copy:
        src: ../Dockerfile
        dest: /opt/docker

    - name: COPY WAR FILE
      copy:
        src: ../webapp/target/webapp.war
        dest: /opt/docker
