---
- name: IMAGE PUSH
  hosts: tag_eks_master_server
  remote_user: ubuntu
  become: yes
  tasks:
    - name: TAG IMAGE WITH BUILD ID & LATEST
      shell: |
        cd /opt/docker
        docker build -t 65.0.110.219:8083/springapp:1 .

    - name: LOGIN DOCKERHUB & PUSH IMAGE ON REGISTRY
      shell: |        
        docker login -u admin -p Prajwal@91 65.0.110.219:8083
        docker push 65.0.110.219:8083/springapp:1 

    - name: REMOVE OLD IMAGES FROM SERVER
      shell: docker rmi -f 65.0.110.219:8083/springapp:1 &> /dev/null
