---
- name: IMAGE PUSH
  hosts: tag_eks_master_server
  remote_user: ubuntu
  become: yes
  tasks:
    - name: TAG IMAGE WITH BUILD ID & LATEST
      shell: |
        cd /opt/docker
        docker build -t prajwal1691/springapp:VERSION .
        docker tag prajwal1691/springapp:VERSION DOCKER_HOSTED/springapp:VERSION
        docker tag prajwal1691/springapp:VERSION prajwal1691/springapp:latest

    - name: LOGIN DOCKERHUB & PUSH IMAGE ON REGISTRY
      shell: |        
        docker login -u admin -p NEXUS_PASSWORD DOCKER_HOSTED
        docker push DOCKER_HOSTED/springapp:VERSION
        docker login -u prajwal1691 -p NEXUS_PASSWORD
        docker push prajwal1691/springapp:VERSION
        docker push prajwal1691/springapp:latest

    - name: REMOVE OLD IMAGES FROM SERVER
      shell: |
        docker rmi -f DOCKER_HOSTED/springapp:VERSION &> /dev/null
        docker rmi -f prajwal1691/springapp:VERSION &> /dev/null
        
